#!/bin/sh

echo -n "Name: "; read name
echo -n "Version: "; read version
echo -n "Description: "; read description
echo -n "Upstream URL: "; read url

mkdir "$name"
cd "$name"

git init

cat > .gitignore <<EOF
*
!.gitignore
!.SRCINFO
!PKGBUILD
EOF

echo "# Maintainer: $(git config user.name) <$(git config user.email)>" > PKGBUILD
echo "pkgname=\"$name\"" >> PKGBUILD
echo "pkgver=$version" >> PKGBUILD
echo "pkgrel=1" >> PKGBUILD
echo "pkgdesc=\"$description\"" >> PKGBUILD
echo "url=\"$url\"" >> PKGBUILD
cat >> PKGBUILD <<EOF
arch=("x86_64")
license=("TODO")
makedepends=()
optdepends=()
depends=()
source=("TODO")
sha256sums=("TODO")

build() {
    cd "\$srcdir/\$pkgname-\$pkgver"
    # make
}
package() {
    cd "\$srcdir/\$pkgname-\$pkgver"
    # install -Dm 755 "bin/\$pkgname" "\$pkgdir/usr/bin/\$pkgname"
}
EOF
