#!/bin/bash

set -e

# Source: https://stackoverflow.com/a/29613573/5069285
quoteSubst() {
  IFS= read -d '' -r < <(sed -e ':a' -e '$!{N;ba' -e '}' -e 's/[&/\]/\\&/g; s/\n/\\&/g' <<<"$1")
  printf %s "${REPLY%$'\n'}"
}
# End

version="$1"

if [ -z "$version" ]; then
    echo "aur-update <version>"
    exit
fi

sed -i "s/^\(pkgver=\).*$/\1$(quoteSubst "$version")/" PKGBUILD
sed -i "s/^\(pkgrel=\).*$/\11/" PKGBUILD
updpkgsums
makepkg --printsrcinfo > .SRCINFO

echo -n "Install new package version? [Y/n] "
read -r input

if [ -z "$input" ] || [ "${input,,}" == "y" ]; then
    makepkg -sri
fi

git diff PKGBUILD .SRCINFO

echo -n "Commit new version? [Y/n] "
read -r input

if [ -z "$input" ] || [ "${input,,}" == "y" ]; then
    git add PKGBUILD .SRCINFO
    git commit -m "Bump version to $version"
fi
